### PR TITLE
fix: Support libraries using TargetFrameworks property

### LINKED ISSUE #11: SDK does not run on projects targeting multiple TFMs
## Repro

1. Create empty project

```pwsh
dotnet new classlib -lang F#
dotnet add package Fable.Package.SDK
```

2. Attempt to pack

```pwsh
# Building will fail
dotnet pack
```

> \fable.package.sdk\1.3.0\build\Fable.Package.SDK.targets(59,9): error : The property FablePackageType must be set to 'library' or 'binding'.

3. Change to use `TargetFrameworks` in fsproj

```xml
    <TargetFrameworks>net9.0;netstandard2.0</TargetFrameworks>
    <!-- <TargetFramework>net9.0</TargetFramework> -->
```

4. Attempt to pack again

```pwsh
# Building will succeed
dotnet pack
```

> Restore complete (0.5s)
  sdk-test netstandard2.0 succeeded (1.1s) → bin\Release\netstandard2.0\sdk-test.dll
  sdk-test net9.0 succeeded (1.4s) → bin\Release\net9.0\sdk-test.dll

### PR DESCRIPTION
**Pull request by roboz0r**
Copies the `build` directory to `buildCrossTargeting` when creating packages so the SDK will work as expected with libraries using `TargetFrameworks` https://github.com/dotnet/msbuild/issues/1860

- Fixes #11

### CODE REVIEW

**Comment by MangelMaxime** [comment]
Hello,

Thanks for the PR could you please add tests too to check that everything works as expected for `TargetFrameworks` too. 

I don't think we need the full suit of test, the following should be enough I think:

- Fail if we don't have the the required tag
- Tags, files, etc. are added if all is configured correctly (can be done in a single test I think)

**Comment by roboz0r** [comment]
Creating a test project like the others in the repo will work but won't demonstrate the fix. Using explicit `Import` like the existing tests works fine without the changes I made. 

The way I tested it manually was:

- Create the `Fable.Package.SDK` package locally with an incremented version number e.g. `1.4.0`
- Create a test project library with `<PackageReference Include="Fable.Package.SDK" Version="1.4.0">`
- Add nuget.config for a local package reference

```xml
<configuration>
  <packageSources>
    <!-- The <clear/> line below removes the global NuGet package sources. -->
    <clear />
    <add key="nuget" value="https://api.nuget.org/v3/index.json" />
    <add key="local" value="C:\Users\Robert\GitHub\sdk-test\packages" />
  </packageSources>
  <packageSourceMapping>
    <!-- key value for <packageSource> should match key values from <packageSources> element -->
    <packageSource key="nuget">
      <package pattern="*" />
    </packageSource>
    <packageSource key="local">
      <package pattern="Fable.Package.SDK" />
    </packageSource>
  </packageSourceMapping>
</configuration>
```

- Run `dotnet pack` on `sdk-test` project to confirm errors without and success with required tags
- Inspect the produced package and confirm the `.fs` files were bundled

I'm not sure if there's a good way to automate this for a test?

**Comment by MangelMaxime** [comment]
> Creating a test project like the others in the repo will work but won't demonstrate the fix. Using explicit `Import` like the existing tests works fine without the changes I made.

Even, by changing `<TargetFramework>netstandard2.0</TargetFramework>` to `<TargetFrameworks>netstandard2.0</TargetFrameworks>` ?

> I'm not sure if there's a good way to automate this for a test?

We could automate all this setup, but this is probably more work for something which is not too worth. If the issue keep happening because we release regression then it could be worth considering in the future. 

Thanks for the PR, I will review it a little later

**Comment by roboz0r** [comment]
Yes, I've published XParsec by using direct `Import` here and using `<TargetFrameworks>net8.0;netstandard2.0</TargetFrameworks>` which is confirmed working as expected.

https://github.com/roboz0r/XParsec/blob/fa8fcff6e37484fd16bee5105a9892faaeefbe01/src/XParsec/XParsec.fsproj#L41-L42

**Comment by roboz0r** [comment]
I've added some basic tests which should identify any regressions that would make the targets multi-tfm incompatible. I didn't go the whole way as I described in the manual testing.

File: tests/Main.fs [hunk 1]
```diff
@@ -38,9 +38,17 @@ let ``Missing FablePackageType property should report an error`` () =
...
+        do!
+            expectToFailWithMessage
+                Workspace.fixtures.invalid.``MissingFableTarget.fsproj``
+                "You need to set at least one of Fable target via the PackageTags property. Possible values are: fable-dart, fable-dotnet, fable-javascript, fable-python, fable-rust, fable-all."
+
+        do!
+            expectToFailWithMessage
+                Workspace.fixtures.invalid.``MissingFableTargetMultiTFM.fsproj``
+                "You need to set at least one of Fable target via the PackageTags property. Possible values are: fable-dart, fable-dotnet, fable-javascript, fable-python, fable-rust, fable-all."
+    }
```
Comment (MangelMaxime) [inline tests/Main.fs]: Please avoid testing 2 thing in the same test. 

This make it difficult to know the exact source of the error

We can create another tests named:

```fs
let ``Missing FableTarget property should report an error - MultiTFM`` () =
```

File: tests/fixtures/valid/library-with-files/packages.lock.json
Comment (MangelMaxime) [inline tests/fixtures/valid/library-with-files/packages.lock.json:1]: Please create another folder to test the Multi TFM, because I think if we have multiple `fsproj` that we `pack` then MSBuild will keep updating the `packages.lock.json`.

This can be annoying because this can generate diff in the git history

File: tests/Main.fs [hunk 2]
```diff
@@ -237,20 +245,46 @@ let ``should include the source file and the project file under 'fable' folder``
...
+
+        let entries = archive.Entries |> Seq.map (fun entry -> entry.FullName) |> Seq.toList
+
+        Assert.That(entries, Contains.Item("fable/Entry.fs"))
+
+        Assert.That(entries, Contains.Item("fable/MyLibraryMultiTFM.fsproj"))
+
+        Assert.That(entries, Contains.Item("lib/netstandard2.0/MyLibraryMultiTFM.dll"))
+
+        Assert.That(entries, Contains.Item("lib/net8.0/MyLibraryMultiTFM.dll"))
```
Comment (MangelMaxime) [inline tests/Main.fs]: Testing for the `dll` presence is not required in theory, because this is the job of .NET to place them correctly.

**Review by MangelMaxime — CHANGES_REQUESTED** [review]

File: tests/Main.fs (hunk 1 above)
Comment (roboz0r) [reply tests/Main.fs]: Done

File: tests/fixtures/valid/library-with-files/packages.lock.json
Comment (roboz0r) [reply tests/fixtures/valid/library-with-files/packages.lock.json:1]: split these into another folder

File: tests/Main.fs (hunk 2 above)
Comment (roboz0r) [reply tests/Main.fs]: removed these checks

**Comment by MangelMaxime** [comment]
Thanks for the PR, it has been released in 1.3.1

**Comment by roboz0r** [comment]
Looks like you went to the effort of the full test simulation. Nice work!

**Comment by MangelMaxime** [comment]
> Looks like you went to the effort of the full test simulation. Nice work!

Yes, I needed to do that because otherwise the test was succeeding even without your fix.
